name: Manual Build

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'build target'
        required: true
        default: 'x86_64'
      test:
        description: 'if test?'
        required: false
        default: 'false'

jobs:
  check:
    runs-on: ubuntu-latest
    name: Manual build ${{matrix.target}}

    steps:
    - name: Get latest tag
      id: getTag
      run: |
        latestTag="$((curl -gs -H 'Content-Type: application/json' \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          -X POST -d '{ "query": "query {repository(owner: \"x-wrt\", name: \"x-wrt\") {refs(refPrefix: \"refs/tags/\", last: 4, orderBy: {field: TAG_COMMIT_DATE, direction: ASC}) {edges {node {name}}}}}"}' https://api.github.com/graphql) | jq -r '.data.repository.refs.edges[].node.name' | grep '22.' | tail -n 1)"
        echo "::set-output name=latestTag::${latestTag}"
        echo "latestTag: $latestTag"

    - name: Trigger normal build
      if: github.event.inputs.test != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: build X-WRT ${{ github.event.inputs.target }} ${{ steps.getTag.outputs.latestTag }}
        client-payload: '{"branch": "${{ steps.getTag.outputs.latestTag }}", "target": "${{ github.event.inputs.target }}", "test": "false"}'
    
    - name: Trigger test
      if: github.event.inputs.test == 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: test X-WRT ${{ github.event.inputs.target }} ${{ steps.getTag.outputs.latestTag }}
        client-payload: '{"branch": "${{ steps.getTag.outputs.latestTag }}", "target": "${{ github.event.inputs.target }}", "test": "true"}'
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 4