name: Repo Dispatcher

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'repo branch or tag'
        required: true
        default: '22.03_b202204240424'
      target:
        description: 'build target'
        required: true
        default: 'x86_64'
      test:
        description: 'if test?'
        required: false
        default: 'false'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Trigger normal build
      if: github.event.inputs.test != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: build X-Wrt ${{ github.event.inputs.target }} ${{ github.event.inputs.branch }}
        client-payload: '{"branch": "${{ github.event.inputs.branch }}", "target": "${{ github.event.inputs.target }}", "test": "false"}'
    
    - name: Trigger test
      if: github.event.inputs.test == 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: test X-Wrt ${{ github.event.inputs.target }} ${{ github.event.inputs.branch }}
        client-payload: '{"branch": "${{ github.event.inputs.branch }}", "target": "${{ github.event.inputs.target }}", "test": "true"}'
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 4