#
# Copyright (c) 2019-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#

name: Repo Dispatcher

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'repo branch or tag'
        required: true
        default: '22.03_b202204240424'
      target:
        description: 'build target'
        required: true
        default: 'x86_64'
      test:
        description: 'if test?'
        required: false
        default: 'false'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Trigger normal build
      if: github.event.inputs.test != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: build X-Wrt ${{ github.event.inputs.target }} ${{ github.event.inputs.branch }}
        client-payload: '{"branch": "${{ github.event.inputs.branch }}", "target": "${{ github.event.inputs.target }}", "test": "false"}'
    
    - name: Trigger test
      if: github.event.inputs.test == 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: test X-Wrt ${{ github.event.inputs.target }} ${{ github.event.inputs.branch }}
        client-payload: '{"branch": "${{ github.event.inputs.branch }}", "target": "${{ github.event.inputs.target }}", "test": "true"}'
        
    - name: Delete workflow runs
      uses: MajorScruffy/delete-workflow-runs
      with:
        repository: ${{ github.repository }}
        maximum-workflow-runs-to-keep: 8